---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  npm: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

install:
  - npm ci

script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
