---
language: node_js
node_js:
  - "6"

dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - bower --version

install:
  - yarn install --non-interactive
  - bower install

script:
  - yarn test
