---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt
  - phantomjs --version
  - bower --version

install:
  - yarn install
  - bower install

script:
  - yarn test
